### ISSUE TITLE
Error during provisioning

### ISSUE THREAD

**Issue by BronsonQuick** [Chassis/Query-Monitor#2]
`Error: /Stage[main]/Querymonitor/Wp::Plugin[query-monitor]/Exec[wp install plugin query-monitor --activate]: Could not evaluate: /usr/bin/env: ‘php’: No such file or directory
[vagrant] ==> default: 
[vagrant] ==> default: Notice: /Stage[main]/Apt/Apt::Setting[conf-update-stamp]/File[/etc/apt/apt.conf.d/15update-stamp]/content: content changed '{md5}b9de0ac9e2c9854b1bb213e362dc4e41' to '{md5}096`

This occurs with the following yaml configuration:
```
paths:
    base: ..
    content: content
    wp: wordpress

hosts:
    - rad.local

# Define database prefix, since we have tests as well
database:
    name: wordpress
    user: wordpress
    password: vagrantpassword
    prefix: wp_

# Define the extensions we want
extensions:
    - chassis/xdebug
    - chassis/tester
    - chassis/sequelpro
    - chassis/cavalcade
    - chassis/mailhog
    - chassis/memcache
    - chassis/phpcs
    - chassis/query-monitor
```
